# Generated by Django 5.0.6 on 2024-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
