# Generated by Django 5.0.6 on 2024-06-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_woman_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='ispublished',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
