# Generated by Django 5.0.6 on 2024-06-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_category_woman_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='categ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category'),
        ),
    ]
