# Generated by Django 5.0.6 on 2024-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_alter_woman_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='marriage_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
