# Generated by Django 5.0.6 on 2024-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_alter_category_options_alter_woman_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media', verbose_name='Фото'),
        ),
    ]
