# Generated by Django 5.0.6 on 2024-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_woman_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
