# Generated by Django 5.0.6 on 2024-09-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_alter_woman_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
