# Generated by Django 5.0.6 on 2024-09-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0015_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
